"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-10-03 16:38:16.603277

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("agency_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("bays", sa.Integer(), nullable=False),
        sa.Column("capacity_hours_per_day", sa.Float(), nullable=False),
        sa.Column("avg_turnaround_days", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "level IN ('line', 'base', 'depot')", name=op.f("ck_agencies_ck_agencies_level_valid")
        ),
        sa.CheckConstraint(
            "avg_turnaround_days > 0", name=op.f("ck_agencies_ck_agencies_turnaround_positive")
        ),
        sa.CheckConstraint("bays >= 1", name=op.f("ck_agencies_ck_agencies_bays_positive")),
        sa.CheckConstraint(
            "capacity_hours_per_day > 0", name=op.f("ck_agencies_ck_agencies_capacity_positive")
        ),
        sa.PrimaryKeyConstraint("agency_id", name=op.f("pk_agencies")),
    )
    op.create_table(
        "aircraft",
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("tail_code", sa.String(length=50), nullable=False),
        sa.Column("type_code", sa.String(length=50), nullable=False),
        sa.Column("commissioned_date", sa.Date(), nullable=False),
        sa.Column("total_flight_hours", sa.Float(), nullable=False),
        sa.Column("total_cycles", sa.Integer(), nullable=False),
        sa.Column("base_id", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "total_cycles >= 0", name=op.f("ck_aircraft_ck_aircraft_cycles_non_negative")
        ),
        sa.CheckConstraint(
            "total_flight_hours >= 0",
            name=op.f("ck_aircraft_ck_aircraft_flight_hours_non_negative"),
        ),
        sa.PrimaryKeyConstraint("aircraft_id", name=op.f("pk_aircraft")),
        sa.UniqueConstraint("tail_code", name=op.f("uq_aircraft_tail_code")),
    )
    op.create_table(
        "model_runs",
        sa.Column("run_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_model_runs")),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_runs")),
    )
    op.create_table(
        "spare_parts",
        sa.Column("part_number", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.Column("unit_cost", sa.Float(), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("reorder_level", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "criticality >= 1 AND criticality <= 5",
            name=op.f("ck_spare_parts_ck_spare_parts_criticality_range"),
        ),
        sa.CheckConstraint(
            "lead_time_days >= 0", name=op.f("ck_spare_parts_ck_spare_parts_lead_time_non_negative")
        ),
        sa.CheckConstraint(
            "reorder_level >= 0",
            name=op.f("ck_spare_parts_ck_spare_parts_reorder_level_non_negative"),
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_spare_parts_ck_spare_parts_unit_cost_non_negative")
        ),
        sa.PrimaryKeyConstraint("part_number", name=op.f("pk_spare_parts")),
    )
    op.create_table(
        "systems",
        sa.Column("system_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("system_id", name=op.f("pk_systems")),
    )
    op.create_table(
        "twin_snapshots",
        sa.Column("snapshot_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("node_type", sa.String(length=50), nullable=False),
        sa.Column("node_id", sa.String(length=50), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("health_index", sa.Float(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("risk", sa.Float(), nullable=True),
        sa.Column("rul_p50", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "node_type IN ('fleet', 'aircraft', 'system', 'component')",
            name=op.f("ck_twin_snapshots_ck_twin_snapshots_node_type_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('Healthy', 'Watch', 'Degraded', 'Critical', 'Failed', 'Under maintenance')",
            name=op.f("ck_twin_snapshots_ck_twin_snapshots_state_valid"),
        ),
        sa.CheckConstraint(
            "health_index >= 0.0 AND health_index <= 100.0",
            name=op.f("ck_twin_snapshots_ck_twin_snapshots_health_index_range"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_twin_snapshots")),
    )
    op.create_index(
        "ix_twin_snapshots_node_id_as_of_date",
        "twin_snapshots",
        ["node_id", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "role IN ('commander', 'planner', 'technician')",
            name=op.f("ck_users_ck_users_role_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "aircraft_daily_status",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('Available', 'Scheduled Maintenance', 'Unscheduled Repair', 'Awaiting Spares', 'Awaiting Workshop')",
            name=op.f("ck_aircraft_daily_status_ck_aircraft_daily_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_aircraft_daily_status_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aircraft_daily_status")),
        sa.UniqueConstraint("aircraft_id", "date", name="uq_aircraft_daily_status_aircraft_date"),
    )
    op.create_index(
        "ix_aircraft_daily_status_aircraft_date",
        "aircraft_daily_status",
        ["aircraft_id", "date"],
        unique=False,
    )
    op.create_table(
        "component_types",
        sa.Column("component_type_id", sa.String(length=50), nullable=False),
        sa.Column("system_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("criticality", sa.Integer(), nullable=False),
        sa.Column("design_life_hours", sa.Float(), nullable=False),
        sa.Column("mtbf_hours", sa.Float(), nullable=False),
        sa.Column("part_number", sa.String(length=50), nullable=False),
        sa.Column("is_repairable", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "criticality >= 1 AND criticality <= 5",
            name=op.f("ck_component_types_ck_component_types_criticality_range"),
        ),
        sa.CheckConstraint(
            "design_life_hours > 0",
            name=op.f("ck_component_types_ck_component_types_design_life_positive"),
        ),
        sa.CheckConstraint(
            "mtbf_hours > 0", name=op.f("ck_component_types_ck_component_types_mtbf_positive")
        ),
        sa.ForeignKeyConstraint(
            ["system_id"],
            ["systems.system_id"],
            name=op.f("fk_component_types_system_id_systems"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("component_type_id", name=op.f("pk_component_types")),
    )
    op.create_table(
        "flights",
        sa.Column("flight_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("duration_hours", sa.Float(), nullable=False),
        sa.Column("cycles", sa.Integer(), nullable=False),
        sa.Column("ambient_temp_c", sa.Float(), nullable=True),
        sa.Column("altitude_band", sa.String(length=50), nullable=True),
        sa.Column("load_factor", sa.Float(), nullable=True),
        sa.CheckConstraint("cycles >= 0", name=op.f("ck_flights_ck_flights_cycles_non_negative")),
        sa.CheckConstraint(
            "duration_hours > 0", name=op.f("ck_flights_ck_flights_duration_positive")
        ),
        sa.CheckConstraint(
            "load_factor IS NULL OR load_factor >= 0",
            name=op.f("ck_flights_ck_flights_load_factor_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_flights_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("flight_id", name=op.f("pk_flights")),
    )
    op.create_index("ix_flights_aircraft_id_date", "flights", ["aircraft_id", "date"], unique=False)
    op.create_table(
        "inventory",
        sa.Column("inventory_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("part_number", sa.String(length=50), nullable=False),
        sa.Column("location_id", sa.String(length=50), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("on_order", sa.Integer(), nullable=False),
        sa.Column("expected_receipt_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "on_hand >= 0", name=op.f("ck_inventory_ck_inventory_on_hand_non_negative")
        ),
        sa.CheckConstraint(
            "on_order >= 0", name=op.f("ck_inventory_ck_inventory_on_order_non_negative")
        ),
        sa.CheckConstraint(
            "reserved >= 0", name=op.f("ck_inventory_ck_inventory_reserved_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["part_number"],
            ["spare_parts.part_number"],
            name=op.f("fk_inventory_part_number_spare_parts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("inventory_id", name=op.f("pk_inventory")),
        sa.UniqueConstraint("part_number", "location_id", name="uq_inventory_part_location"),
    )
    op.create_index(
        "ix_inventory_part_number_location_id",
        "inventory",
        ["part_number", "location_id"],
        unique=False,
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("task_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("task_name", sa.String(length=100), nullable=False),
        sa.Column("interval_hours", sa.Float(), nullable=False),
        sa.Column("last_done_hours", sa.Float(), nullable=False),
        sa.Column("due_hours", sa.Float(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "due_hours >= 0",
            name=op.f("ck_scheduled_tasks_ck_scheduled_tasks_due_hours_non_negative"),
        ),
        sa.CheckConstraint(
            "interval_hours > 0",
            name=op.f("ck_scheduled_tasks_ck_scheduled_tasks_interval_positive"),
        ),
        sa.CheckConstraint(
            "last_done_hours >= 0",
            name=op.f("ck_scheduled_tasks_ck_scheduled_tasks_last_done_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_scheduled_tasks_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_scheduled_tasks")),
    )
    op.create_table(
        "components",
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=True),
        sa.Column("component_type_id", sa.String(length=50), nullable=False),
        sa.Column("serial_no", sa.String(length=50), nullable=False),
        sa.Column("installed_date", sa.Date(), nullable=True),
        sa.Column("hours_at_install", sa.Float(), nullable=False),
        sa.Column("hours_since_new", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "status IN ('installed', 'in_stock', 'under_repair', 'scrapped')",
            name=op.f("ck_components_ck_components_status_valid"),
        ),
        sa.CheckConstraint(
            "hours_at_install >= 0",
            name=op.f("ck_components_ck_components_hours_at_install_non_negative"),
        ),
        sa.CheckConstraint(
            "hours_since_new >= 0",
            name=op.f("ck_components_ck_components_hours_since_new_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_components_aircraft_id_aircraft"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["component_type_id"],
            ["component_types.component_type_id"],
            name=op.f("fk_components_component_type_id_component_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("component_id", name=op.f("pk_components")),
        sa.UniqueConstraint("serial_no", name=op.f("uq_components_serial_no")),
    )
    op.create_table(
        "advisories",
        sa.Column("advisory_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("dismiss_reason", sa.Text(), nullable=True),
        sa.Column("explanation", sa.JSON(), nullable=True),
        sa.Column("spare_status", sa.String(length=100), nullable=True),
        sa.Column("expected_downtime_days", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "priority IN ('P1', 'P2', 'P3', 'P4')",
            name=op.f("ck_advisories_ck_advisories_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('proposed', 'accepted', 'scheduled', 'completed', 'dismissed')",
            name=op.f("ck_advisories_ck_advisories_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_advisories_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("advisory_id", name=op.f("pk_advisories")),
    )
    op.create_index(
        "ix_advisories_component_as_of_date",
        "advisories",
        ["component_id", "as_of_date"],
        unique=False,
    )
    op.create_index(
        "ix_advisories_status_priority", "advisories", ["status", "priority"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("alert_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=True),
        sa.Column("component_id", sa.String(length=50), nullable=True),
        sa.Column("advisory_id", sa.String(length=50), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_alerts_ck_alerts_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_alerts_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_alerts_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("alert_id", name=op.f("pk_alerts")),
    )
    op.create_index(
        "ix_alerts_severity_acknowledged", "alerts", ["severity", "acknowledged"], unique=False
    )
    op.create_table(
        "anomaly_scores",
        sa.Column("score_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("flight_id", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("top_parameters", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_anomaly_scores_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.flight_id"],
            name=op.f("fk_anomaly_scores_flight_id_flights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("score_id", name=op.f("pk_anomaly_scores")),
    )
    op.create_index(
        "ix_anomaly_scores_component_flight",
        "anomaly_scores",
        ["component_id", "flight_id"],
        unique=False,
    )
    op.create_table(
        "fault_events",
        sa.Column("event_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fault_code", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')",
            name=op.f("ck_fault_events_ck_fault_events_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_fault_events_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_fault_events_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_fault_events")),
    )
    op.create_index(
        "ix_fault_events_aircraft_timestamp",
        "fault_events",
        ["aircraft_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_fault_events_component_timestamp",
        "fault_events",
        ["component_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "predictions",
        sa.Column("prediction_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("risk_14d", sa.Float(), nullable=False),
        sa.Column("risk_30d", sa.Float(), nullable=False),
        sa.Column("rul_p10", sa.Float(), nullable=False),
        sa.Column("rul_p50", sa.Float(), nullable=False),
        sa.Column("rul_p90", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "risk_14d >= 0.0 AND risk_14d <= 1.0",
            name=op.f("ck_predictions_ck_predictions_risk_14d_range"),
        ),
        sa.CheckConstraint(
            "risk_30d >= 0.0 AND risk_30d <= 1.0",
            name=op.f("ck_predictions_ck_predictions_risk_30d_range"),
        ),
        sa.CheckConstraint(
            "rul_p10 <= rul_p50 AND rul_p50 <= rul_p90",
            name=op.f("ck_predictions_ck_predictions_rul_quantiles_monotonic"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_predictions_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_predictions")),
        sa.UniqueConstraint(
            "component_id",
            "as_of_date",
            "model_version",
            name="uq_predictions_component_date_version",
        ),
    )
    op.create_index(
        "ix_predictions_component_as_of_date",
        "predictions",
        ["component_id", "as_of_date"],
        unique=False,
    )
    op.create_table(
        "sensor_readings",
        sa.Column("reading_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("flight_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("parameter", sa.String(length=50), nullable=False),
        sa.Column("mean", sa.Float(), nullable=False),
        sa.Column("max", sa.Float(), nullable=False),
        sa.Column("min", sa.Float(), nullable=False),
        sa.Column("std", sa.Float(), nullable=False),
        sa.Column("quality_flag", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "quality_flag IN ('valid', 'dropout', 'stuck', 'drift', 'spike', 'missing')",
            name=op.f("ck_sensor_readings_ck_sensor_readings_quality_flag_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_sensor_readings_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["flight_id"],
            ["flights.flight_id"],
            name=op.f("fk_sensor_readings_flight_id_flights"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("reading_id", name=op.f("pk_sensor_readings")),
    )
    op.create_index(
        "ix_sensor_readings_component_id_flight_id",
        "sensor_readings",
        ["component_id", "flight_id"],
        unique=False,
    )
    op.create_index("ix_sensor_readings_flight_id", "sensor_readings", ["flight_id"], unique=False)
    op.create_table(
        "simulation_truth",
        sa.Column("truth_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("true_health", sa.Float(), nullable=False),
        sa.Column("degradation_phase", sa.String(length=50), nullable=True),
        sa.Column("is_failed", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "true_health >= 0.0 AND true_health <= 1.0",
            name=op.f("ck_simulation_truth_ck_simulation_truth_health_range"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_simulation_truth_component_id_components"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("truth_id", name=op.f("pk_simulation_truth")),
        comment="GROUND TRUTH FOR EVALUATION ONLY - DO NOT USE FOR MODEL TRAINING",
    )
    op.create_index(
        "ix_simulation_truth_component_date",
        "simulation_truth",
        ["component_id", "date"],
        unique=False,
    )
    op.create_table(
        "work_orders",
        sa.Column("wo_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=True),
        sa.Column("advisory_id", sa.String(length=50), nullable=True),
        sa.Column("agency_id", sa.String(length=50), nullable=False),
        sa.Column("opened", sa.DateTime(timezone=True), nullable=False),
        sa.Column("planned_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promised_done", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_done", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("delay_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "priority IN ('P1', 'P2', 'P3', 'P4')",
            name=op.f("ck_work_orders_ck_work_orders_priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'in_progress', 'awaiting_spares', 'awaiting_agency', 'completed', 'cancelled')",
            name=op.f("ck_work_orders_ck_work_orders_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.agency_id"],
            name=op.f("fk_work_orders_agency_id_agencies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_work_orders_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_work_orders_component_id_components"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("wo_id", name=op.f("pk_work_orders")),
    )
    op.create_index("ix_work_orders_aircraft_id", "work_orders", ["aircraft_id"], unique=False)
    op.create_index(
        "ix_work_orders_status_agency_id", "work_orders", ["status", "agency_id"], unique=False
    )
    op.create_table(
        "inventory_transactions",
        sa.Column("txn_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("part_number", sa.String(length=50), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("work_order_id", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "type IN ('issue', 'receipt', 'repair-return', 'adjustment')",
            name=op.f("ck_inventory_transactions_ck_inventory_transactions_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["part_number"],
            ["spare_parts.part_number"],
            name=op.f("fk_inventory_transactions_part_number_spare_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.wo_id"],
            name=op.f("fk_inventory_transactions_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("txn_id", name=op.f("pk_inventory_transactions")),
    )
    op.create_index(
        "ix_inventory_transactions_part_date",
        "inventory_transactions",
        ["part_number", "date"],
        unique=False,
    )
    op.create_table(
        "maintenance_events",
        sa.Column("event_id", sa.String(length=50), nullable=False),
        sa.Column("aircraft_id", sa.String(length=50), nullable=False),
        sa.Column("component_id", sa.String(length=50), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("labor_hours", sa.Float(), nullable=False),
        sa.Column("work_order_id", sa.String(length=50), nullable=True),
        sa.Column("root_cause", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "action IN ('replace', 'repair', 'inspect', 'defer')",
            name=op.f("ck_maintenance_events_ck_maintenance_events_action_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('scheduled', 'unscheduled', 'inspection')",
            name=op.f("ck_maintenance_events_ck_maintenance_events_type_valid"),
        ),
        sa.CheckConstraint(
            '"end" IS NULL OR "end" >= "start"',
            name=op.f("ck_maintenance_events_ck_maintenance_events_end_after_start"),
        ),
        sa.CheckConstraint(
            "labor_hours >= 0",
            name=op.f("ck_maintenance_events_ck_maintenance_events_labor_hours_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["aircraft_id"],
            ["aircraft.aircraft_id"],
            name=op.f("fk_maintenance_events_aircraft_id_aircraft"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["components.component_id"],
            name=op.f("fk_maintenance_events_component_id_components"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.wo_id"],
            name=op.f("fk_maintenance_events_work_order_id_work_orders"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_maintenance_events")),
    )
    op.create_index(
        "ix_maintenance_events_aircraft_start",
        "maintenance_events",
        ["aircraft_id", "start"],
        unique=False,
    )
    op.create_index(
        "ix_maintenance_events_component_start",
        "maintenance_events",
        ["component_id", "start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_maintenance_events_component_start", table_name="maintenance_events")
    op.drop_index("ix_maintenance_events_aircraft_start", table_name="maintenance_events")
    op.drop_table("maintenance_events")
    op.drop_index("ix_inventory_transactions_part_date", table_name="inventory_transactions")
    op.drop_table("inventory_transactions")
    op.drop_index("ix_work_orders_status_agency_id", table_name="work_orders")
    op.drop_index("ix_work_orders_aircraft_id", table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index("ix_simulation_truth_component_date", table_name="simulation_truth")
    op.drop_table("simulation_truth")
    op.drop_index("ix_sensor_readings_flight_id", table_name="sensor_readings")
    op.drop_index("ix_sensor_readings_component_id_flight_id", table_name="sensor_readings")
    op.drop_table("sensor_readings")
    op.drop_index("ix_predictions_component_as_of_date", table_name="predictions")
    op.drop_table("predictions")
    op.drop_index("ix_fault_events_component_timestamp", table_name="fault_events")
    op.drop_index("ix_fault_events_aircraft_timestamp", table_name="fault_events")
    op.drop_table("fault_events")
    op.drop_index("ix_anomaly_scores_component_flight", table_name="anomaly_scores")
    op.drop_table("anomaly_scores")
    op.drop_index("ix_alerts_severity_acknowledged", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index("ix_advisories_status_priority", table_name="advisories")
    op.drop_index("ix_advisories_component_as_of_date", table_name="advisories")
    op.drop_table("advisories")
    op.drop_table("components")
    op.drop_table("scheduled_tasks")
    op.drop_index("ix_inventory_part_number_location_id", table_name="inventory")
    op.drop_table("inventory")
    op.drop_index("ix_flights_aircraft_id_date", table_name="flights")
    op.drop_table("flights")
    op.drop_table("component_types")
    op.drop_index("ix_aircraft_daily_status_aircraft_date", table_name="aircraft_daily_status")
    op.drop_table("aircraft_daily_status")
    op.drop_table("users")
    op.drop_index("ix_twin_snapshots_node_id_as_of_date", table_name="twin_snapshots")
    op.drop_table("twin_snapshots")
    op.drop_table("systems")
    op.drop_table("spare_parts")
    op.drop_table("scenario_runs")
    op.drop_table("model_runs")
    op.drop_table("aircraft")
    op.drop_table("agencies")
    # ### end Alembic commands ###
